test.AddQuestion( new Question ("ec_final_q1",
                                "Which feature of Claude Enterprise allows users to view and interact with code, documents, and websites in a dedicated side-by-side window?",
                                QUESTION_TYPE_CHOICE,
                                new Array("Artifacts", "Admin Console", "SSO", "SCIM"),
                                "Artifacts",
                                "obj_final")
                );

test.AddQuestion( new Question ("ec_final_q2",
                                "Which security feature allows administrators to restrict Claude access to specific corporate IP addresses?",
                                QUESTION_TYPE_CHOICE,
                                new Array("Domain Capture", "SCIM", "SAML 2.0", "IP Allowlisting"),
                                "IP Allowlisting",
                                "obj_final")
                );

test.AddQuestion( new Question ("ec_final_q3",
                                "How does the 'Projects' feature facilitate team collaboration in Claude Enterprise?",
                                QUESTION_TYPE_CHOICE,
                                new Array("By bypassing SSO requirements", "By allowing shared document sets and custom instructions for specific workstreams", "By increasing the context window for all users", "By automating user billing"),
                                "By allowing shared document sets and custom instructions for specific workstreams",
                                "obj_final")
                );

test.AddQuestion( new Question ("ec_final_q4",
                                "Which feature allows an administrator to define a custom message that all users see when they log into Claude for the first time?",
                                QUESTION_TYPE_CHOICE,
                                new Array("SCIM Protocol", "Custom Onboarding Message", "Organization Policy", "Workspace Logo"),
                                "Custom Onboarding Message",
                                "obj_final")
                );

test.AddQuestion( new Question ("ec_final_q5",
                                "When using Claude Enterprise, who owns the Intellectual Property (IP) of the outputs generated by the model according to the default agreement?",
                                QUESTION_TYPE_CHOICE,
                                new Array("The individual user only", "The Customer (Organization)", "Anthropic", "The public domain"),
                                "The Customer (Organization)",
                                "obj_final")
                );

test.AddQuestion( new Question ("ec_final_q6",
                                "Which compliance standard is met by Anthropic to support healthcare-related use cases?",
                                QUESTION_TYPE_CHOICE,
                                new Array("HIPAA", "PCI-DSS", "GDPR", "FERPA"),
                                "HIPAA",
                                "obj_final")
                );

test.AddQuestion( new Question ("ec_final_q7",
                                "How can an organization ensure that their custom branding is visible to all users in Claude?",
                                QUESTION_TYPE_CHOICE,
                                new Array("It is not possible to customize branding", "By using a Chrome Extension", "By editing the Claude source code", "By configuring the Organization Profile in the Admin Console"),
                                "By configuring the Organization Profile in the Admin Console",
                                "obj_final")
                );

test.AddQuestion( new Question ("ec_final_q8",
                                "Which encryption standard is used by Anthropic to protect data at rest?",
                                QUESTION_TYPE_CHOICE,
                                new Array("RSA-1024", "MD5", "AES-256", "DES"),
                                "AES-256",
                                "obj_final")
                );

test.AddQuestion( new Question ("ec_final_q9",
                                "A company wants to ensure that HR data is never accessible to the Engineering team within Claude. What is the best strategy?",
                                QUESTION_TYPE_CHOICE,
                                new Array("Use different passwords for each team", "Create separate Workspaces for HR and Engineering", "Rename all HR documents", "Ask employees to be careful"),
                                "Create separate Workspaces for HR and Engineering",
                                "obj_final")
                );

test.AddQuestion( new Question ("ec_final_q10",
                                "What is 'Domain Capture' in the context of user provisioning?",
                                QUESTION_TYPE_CHOICE,
                                new Array("Automatically adding any user with a verified company email domain to the organization", "Capturing website URLs to process as data", "Blocking competitors from accessing your website", "Buying all similar-sounding domain names"),
                                "Automatically adding any user with a verified company email domain to the organization",
                                "obj_final")
                );

test.AddQuestion( new Question ("ec_final_q11",
                                "What does a 'Viewer' role typically allow a user to do in the Admin Console?",
                                QUESTION_TYPE_CHOICE,
                                new Array("Change API keys", "Delete users", "Read-only access to dashboards and usage data", "Invite new members"),
                                "Read-only access to dashboards and usage data",
                                "obj_final")
                );

test.AddQuestion( new Question ("ec_final_q12",
                                "How is 'Encryption in Transit' implemented in Enterprise Claude?",
                                QUESTION_TYPE_CHOICE,
                                new Array("Using TLS 1.3", "Using base64 encoding", "Via private VPNs only", "Via physical couriers"),
                                "Using TLS 1.3",
                                "obj_final")
                );

test.AddQuestion( new Question ("ec_final_q13",
                                "Which feature allows users to share a collection of documents and prompts within a specific team without making them organization-wide?",
                                QUESTION_TYPE_CHOICE,
                                new Array("Billing Admin", "Public URLs", "Projects", "Global Settings"),
                                "Projects",
                                "obj_final")
                );

test.AddQuestion( new Question ("ec_final_q14",
                                "What happens when a user is removed from a group in the Identity Provider (IdP) if SCIM is enabled?",
                                QUESTION_TYPE_CHOICE,
                                new Array("They are sent a warning email", "Nothing happens until the admin manually deletes them", "Their Claude account is instantly and automatically de-provisioned", "Their password is changed"),
                                "Their Claude account is instantly and automatically de-provisioned",
                                "obj_final")
                );

test.AddQuestion( new Question ("ec_final_q15",
                                "Why would an organization use Activity Logs?",
                                QUESTION_TYPE_CHOICE,
                                new Array("To track how many hours employees spend on lunch", "To find out who is the most popular employee", "To read private conversations between employees", "To maintain an audit trail of feature access and settings changes for compliance"),
                                "To maintain an audit trail of feature access and settings changes for compliance",
                                "obj_final")
                );
